INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Австралийский доллар/Канадский доллар','AUDCAD','AC','ACD',false,NULL,20,NULL)
,('Австралийский доллар/Швейцарский франк','AUDCHF','none','none',false,NULL,NULL,NULL)
,('Австралийский доллар/Новозеландский доллар','AUDNZD','AN','ANE',false,NULL,20,NULL)
,('Австралийский доллар/Японская Йена','AUDJPY','AJ','AJY',false,NULL,2000,NULL)
,('Австралийский доллар/Доллар США','AUDUSD','AD','6A',false,NULL,10,NULL)
,('Канадский доллар/Швейцарский франк','CADCHF','none','none',false,NULL,NULL,NULL)
,('Канадский доллар/Японская Йена','CADJPY','CY','CJY',false,NULL,2000,NULL)
,('Швейцарский франк/Болгарский лев','CHFBGN','none','none',false,NULL,NULL,NULL)
,('Швейцарский франк/Японская Йена','CHFJPY','SJ','SJY',false,NULL,1250,NULL)
,('Швейцарский франк/Новый лей','CHFRON','none','none',false,NULL,NULL,NULL)
;
INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Швейцарский франк/Турецкая лира','CHFTRY','none','none',false,NULL,NULL,NULL)
,('Евро/Австралийский доллар','EURAUD','CA','EAD',false,NULL,12.5,NULL)
,('Евро/Канадский доллар','EURCAD','CC','ECD',false,NULL,12.5,NULL)
,('Евро/Швейцарский франк','EURCHF','RF','RF',false,NULL,12.5,NULL)
,('Евро/Чешская крона','EURCZK','none','none',false,NULL,NULL,NULL)
,('Евро/Датская крона','EURDKK','none','none',false,NULL,NULL,NULL)
,('Евро/Британский фунт стерлингов','EURGBP','RP','RP',false,NULL,12.5,NULL)
,('Евро/Гонконгский доллар','EURHKD','none','none',false,NULL,NULL,NULL)
,('Евро/Венгерский форинт','EURHUF','none','none',false,NULL,NULL,NULL)
,('Евро/Новый израильский шекель','EURILS','none','none',false,NULL,NULL,NULL)
;
INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Евро/Японская Йена','EURJPY','RY','RY',false,NULL,1250,NULL)
,('Евро/Мексиканское песо','EURMXN','none','none',false,NULL,NULL,NULL)
,('Евро/Норвежская крона','EURNOK','CN','ENK',false,NULL,125,NULL)
,('Евро/Новозеландский доллар','EURNZD','none','none',false,NULL,NULL,NULL)
,('Евро/Польский Злотый','EURPLN','none','none',false,NULL,NULL,NULL)
,('Евро/Новый лей','EURRON','none','none',false,NULL,NULL,NULL)
,('Евро/Российский рубль','EURRUB','none','none',false,NULL,NULL,NULL)
,('Евро/Шведская крона','EURSEK','KE','ESK',false,NULL,62.5,NULL)
,('Евро/Сингапурский доллар','EURSGD','none','none',false,NULL,NULL,NULL)
,('Евро/Турецкая лира','EURTRY','none','none',false,NULL,NULL,NULL)
;
INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Евро/Доллар США','EURUSD','EC','6E',false,NULL,12.5,NULL)
,('Евро/Рэнд','EURZAR','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Австралийский доллар','GBPAUD','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Болгарский лев','GBPBGN','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Канадский доллар','GBPCAD','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Швейцарский франк','GBPCHF','BF','PSF',false,NULL,12.5,NULL)
,('Британский фунт стерлингов/Чешская крона','GBPCZK','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Датская крона','GBPDKK','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Гонконгский доллар','GBPHKD','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Доллар США','GBPUSD','BP','6B',false,NULL,6.25,NULL)
;
INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Британский фунт стерлингов/Венгерский форинт','GBPHUF','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Японская Йена','GBPJPY','BY','PJY',false,NULL,1250,NULL)
,('Британский фунт стерлингов/Норвежская крона','GBPNOK','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Новозеландский доллар','GBPNZD','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Польский Злотый','GBPPLN','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Новый лей','GBPRON','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Шведская крона','GBPSEK','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Турецкая лира','GBPTRY','none','none',false,NULL,NULL,NULL)
,('Британский фунт стерлингов/Рэнд','GBPZAR','none','none',false,NULL,NULL,NULL)
,('Гонконгский доллар/Японская Йена','HKDJPY','none','none',false,NULL,NULL,NULL)
;
INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Мексиканское песо/Японская Йена','MXNJPY','none','none',false,NULL,NULL,NULL)
,('Новозеландский доллар/Канадский доллар','NZDCAD','none','none',false,NULL,NULL,NULL)
,('Новозеландский доллар/Швейцарский франк','NZDCHF','none','none',false,NULL,NULL,NULL)
,('Новозеландский доллар/Японская Йена','NZDJPY','none','none',false,NULL,NULL,NULL)
,('Новозеландский доллар/Доллар США','NZDUSD','NE','6N',false,NULL,10,NULL)
,('Сингапурский доллар/Гонконгский доллар','SGDHKD','none','none',false,NULL,NULL,NULL)
,('Сингапурский доллар/Японская Йена','SGDJPY','none','none',false,NULL,NULL,NULL)
,('Турецкая лира/Болгарский лев','TRYBGN','none','none',false,NULL,NULL,NULL)
,('Турецкая лира/Японская Йена','TRYJPY','none','none',false,NULL,NULL,NULL)
,('Турецкая лира/Новый лей','TRYRON','none','none',false,NULL,NULL,NULL)
;
INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Доллар США/Чешская крона','USDCZK','none','none',true,NULL,NULL,NULL)
,('Доллар США/Датская крона','USDDKK','none','none',true,NULL,NULL,NULL)
,('Доллар США/Гонконгский доллар','USDHKD','none','none',true,NULL,NULL,NULL)
,('Доллар США/Венгерский форинт','USDHUF','none','none',true,NULL,NULL,NULL)
,('Доллар США/Канадский доллар','USDCAD','C1','6C',true,0.0000999999975,10,NULL)
,('Доллар США/Новый израильский шекель','USDILS','none','none',true,NULL,NULL,NULL)
,('Доллар США/Мексиканское песо','USDMXN','MP','6M',true,0.0000999999975,5,NULL)
,('Доллар США/Польский Злотый','USDPLN','none','none',true,NULL,NULL,NULL)
,('Доллар США/Новый лей','USDRON','none','none',true,NULL,NULL,NULL)
,('Доллар США/Российский рубль','USDRUB','RU','6R',true,0.0000999999975,25,NULL)
;
INSERT INTO currency ("name",short_name,clearing_code,futures_code,inverted,future_point,price_per_contract,k) VALUES
('Доллар США/Шведская крона','USDSEK','SE','SEK',true,0.0000999999975,20,NULL)
,('Доллар США/Сингапурский доллар','USDSGD','none','none',true,NULL,NULL,NULL)
,('Доллар США/Турецкая лира','USDTRY','none','none',true,NULL,NULL,NULL)
,('Доллар США/Рэнд','USDZAR','none','none',true,NULL,NULL,NULL)
,('Болгарский лев/Новый лей','BGNRON','none','none',true,NULL,NULL,NULL)
,('Серебро/Доллар США','XAGUSD','SI','none',false,NULL,50,NULL)
,('Доллар США/Японская йена','USDJPY','J1','6J',true,0.00000999999975,12.5,NULL)
,('Доллар США/Швейцарский франк','USDCHF','E1','6S',true,0.0000999999975,12.5,NULL)
,('Доллар США/Норвежская крона','USDNOK','UN','NOK',true,0.00000999999975,20,NULL)
,('Золото/Доллар США','XAUUSD','GC','none',false,NULL,1,10)
;
