INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (1,'Австралийский доллар/Канадский доллар','AUDCAD','AC','ACD',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (2,'Австралийский доллар/Швейцарский франк','AUDCHF','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (4,'Австралийский доллар/Новозеландский доллар','AUDNZD','AN','ANE',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (3,'Австралийский доллар/Японская Йена','AUDJPY','AJ','AJY',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (5,'Австралийский доллар/Доллар США','AUDUSD','AD','6A',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (6,'Канадский доллар/Швейцарский франк','CADCHF','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (7,'Канадский доллар/Японская Йена','CADJPY','CY','CJY',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (8,'Швейцарский франк/Болгарский лев','CHFBGN','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (9,'Швейцарский франк/Японская Йена','CHFJPY','SJ','SJY',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (10,'Швейцарский франк/Новый лей','CHFRON','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (11,'Швейцарский франк/Турецкая лира','CHFTRY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (12,'Евро/Австралийский доллар','EURAUD','CA','EAD',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (13,'Евро/Канадский доллар','EURCAD','CC','ECD',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (14,'Евро/Швейцарский франк','EURCHF','RF','RF',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (15,'Евро/Чешская крона','EURCZK','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (16,'Евро/Датская крона','EURDKK','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (17,'Евро/Британский фунт стерлингов','EURGBP','RP','RP',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (18,'Евро/Гонконгский доллар','EURHKD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (19,'Евро/Венгерский форинт','EURHUF','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (20,'Евро/Новый израильский шекель','EURILS','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (21,'Евро/Японская Йена','EURJPY','RY','RY',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (22,'Евро/Мексиканское песо','EURMXN','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (23,'Евро/Норвежская крона','EURNOK','CN','ENK',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (24,'Евро/Новозеландский доллар','EURNZD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (25,'Евро/Польский Злотый','EURPLN','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (26,'Евро/Новый лей','EURRON','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (27,'Евро/Российский рубль','EURRUB','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (28,'Евро/Шведская крона','EURSEK','KE','ESK',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (29,'Евро/Сингапурский доллар','EURSGD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (30,'Евро/Турецкая лира','EURTRY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (31,'Евро/Доллар США','EURUSD','EC','6E',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (32,'Евро/Рэнд','EURZAR','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (33,'Британский фунт стерлингов/Австралийский доллар','GBPAUD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (34,'Британский фунт стерлингов/Болгарский лев','GBPBGN','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (35,'Британский фунт стерлингов/Канадский доллар','GBPCAD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (36,'Британский фунт стерлингов/Швейцарский франк','GBPCHF','BF','PSF',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (37,'Британский фунт стерлингов/Чешская крона','GBPCZK','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (38,'Британский фунт стерлингов/Датская крона','GBPDKK','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (39,'Британский фунт стерлингов/Гонконгский доллар','GBPHKD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (40,'Британский фунт стерлингов/Доллар США','GBPUSD','BP','6B',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (41,'Британский фунт стерлингов/Венгерский форинт','GBPHUF','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (42,'Британский фунт стерлингов/Японская Йена','GBPJPY','BY','PJY',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (43,'Британский фунт стерлингов/Норвежская крона','GBPNOK','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (44,'Британский фунт стерлингов/Новозеландский доллар','GBPNZD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (45,'Британский фунт стерлингов/Польский Злотый','GBPPLN','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (46,'Британский фунт стерлингов/Новый лей','GBPRON','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (47,'Британский фунт стерлингов/Шведская крона','GBPSEK','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (48,'Британский фунт стерлингов/Турецкая лира','GBPTRY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (49,'Британский фунт стерлингов/Доллар США','GBPUSD','BP','6B',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (50,'Британский фунт стерлингов/Рэнд','GBPZAR','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (51,'Гонконгский доллар/Японская Йена','HKDJPY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (52,'Мексиканское песо/Японская Йена','MXNJPY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (53,'Новозеландский доллар/Канадский доллар','NZDCAD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (54,'Новозеландский доллар/Швейцарский франк','NZDCHF','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (55,'Новозеландский доллар/Японская Йена','NZDJPY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (56,'Новозеландский доллар/Доллар США','NZDUSD','NE','6N',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (57,'Сингапурский доллар/Гонконгский доллар','SGDHKD','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (58,'Сингапурский доллар/Японская Йена','SGDJPY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (59,'Турецкая лира/Болгарский лев','TRYBGN','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (60,'Турецкая лира/Японская Йена','TRYJPY','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (61,'Турецкая лира/Новый лей','TRYRON','none','none',false);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (62,'Доллар США/Канадский доллар','USDCAD','C1','6C',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (63,'Доллар США/Швейцарский франк','USDCHF','E1','6S',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (64,'Доллар США/Чешская крона','USDCZK','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (65,'Доллар США/Датская крона','USDDKK','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (66,'Доллар США/Гонконгский доллар','USDHKD','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (67,'Доллар США/Венгерский форинт','USDHUF','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (68,'Доллар США/Новый израильский шекель','USDILS','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (69,'Доллар США/Японская йена','USDJPY','J1','6J',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (70,'Доллар США/Мексиканское песо','USDMXN','MP','6M',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (71,'Доллар США/Норвежская крона','USDNOK','UN','NOK',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (72,'Доллар США/Польский Злотый','USDPLN','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (73,'Доллар США/Новый лей','USDRON','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (74,'Доллар США/Российский рубль','USDRUB','RU','6R',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (75,'Доллар США/Шведская крона','USDSEK','SE','SEK',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (76,'Доллар США/Сингапурский доллар','USDSGD','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (77,'Доллар США/Турецкая лира','USDTRY','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (78,'Доллар США/Рэнд','USDZAR','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (79,'Болгарский лев/Новый лей','BGNRON','none','none',true);
INSERT INTO public.currency (id, name, short_name, clearing_code, futures_code, inverted) VALUES (80,'Золото/Доллар США','XAUUSD','GC','none',false);
